name: Scheduled Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # 每天午夜（UTC 0 点）执行
  workflow_dispatch:       # 可手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "This is a scheduled task"
